import { chromium } from 'playwright-core';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await (await browser.newContext({ viewport: { width: 1600, height: 1000 } })).newPage();
await page.goto('http://localhost:5173/');
await page.evaluate(() => localStorage.clear());
await page.reload();
await page.fill('input[placeholder="e.g. Beth"]', 'Cat');
await page.click('.tmpl:has-text("Catan")');
await page.click('button.primary:has-text("Start a new table")');
await page.waitForSelector('.viewport');
await page.waitForTimeout(900);
const room = await page.evaluate(() => location.hash.replace('#/t/', ''));
const state = () => page.evaluate((r) => JSON.parse(localStorage.getItem(`ludwig:table:${r}`)), room);
let s = await state();
let sb = Object.values(s.entities).find((e) => e.kind === 'scoreboard');
await page.mouse.click(sb.pos.x + 60, sb.pos.y + 8 + 44, { button: 'right' });
await page.click('.menu button:has-text("my view only")');
await page.waitForTimeout(700);
// drag to empty felt
await page.mouse.move(sb.pos.x + 60, sb.pos.y + 8 + 44);
await page.mouse.down();
await page.mouse.move(sb.pos.x + 90, sb.pos.y + 368 + 44, { steps: 6 });
await page.mouse.up();
await page.waitForTimeout(700);
const ov = (await page.evaluate((r) => JSON.parse(localStorage.getItem(`ludwig:pos:${r}`) ?? '{}'), room));
console.log('override:', ov);
const at = Object.values(ov)[0];
const probe = await page.evaluate(([x, y]) => document.elementsFromPoint(x, y).map(el => el.className + '|' + (el.dataset?.entityId ?? '')), [at.x + 60, at.y + 20 + 44]);
console.log('at point:', probe.slice(0, 5));
